prism_finops:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'PRISM_ADMIN_ROLE') }}"
      database: FEDERAL_FINANCIAL_DATA
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'PRISM_APP_WH') }}"
      schema: EOTSS_STAGING
      threads: 4
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'PRISM_ADMIN_ROLE') }}"
      database: FEDERAL_FINANCIAL_DATA
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'PRISM_APP_WH') }}"
      schema: EOTSS_STAGING
      threads: 4
