import PrismLayout from "@/components/PrismLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import { trpc } from "@/lib/trpc";
import {
  FileText,
  RefreshCw,
  Download,
  ChevronRight,
  ChevronDown,
  Building2,
  Globe,
  Briefcase,
  Check,
  AlertCircle,
  Sparkles,
  Shield,
  Users,
  Eye,
  Copy,
  BookOpen,
  Database,
  AlertTriangle,
  Info,
  Lock,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { getLoginUrl } from "@/const";
import { Streamdown } from "streamdown";

type TrustState = "draft" | "internal" | "client" | "executive";

const trustStates: { value: TrustState; label: string; icon: React.ElementType; color: string; description: string }[] = [
  { value: "draft", label: "Draft", icon: FileText, color: "#8b949e", description: "Working document" },
  { value: "internal", label: "Internal", icon: Users, color: "#58a6ff", description: "Team review" },
  { value: "client", label: "Client", icon: Eye, color: "#d29922", description: "Stakeholder ready" },
  { value: "executive", label: "Executive", icon: Shield, color: "#3fb950", description: "C-suite approved" },
];

export default function ExecutiveReports() {
  const { isAuthenticated, user } = useAuth();
  const [scope, setScope] = useState<"agency" | "portfolio" | "government-wide">("government-wide");
  const [selectedAgency, setSelectedAgency] = useState<string | undefined>(undefined);
  const [narrative, setNarrative] = useState<any>(null);
  const [showPromoteDialog, setShowPromoteDialog] = useState(false);
  const [targetTrustState, setTargetTrustState] = useState<TrustState>("internal");
  const [approvalNotes, setApprovalNotes] = useState("");
  const [showEvidenceDetails, setShowEvidenceDetails] = useState(false);

  const { data: agencies, isLoading: loadingAgencies } = trpc.prism.getAgencies.useQuery();

  const generateMutation = trpc.prism.generateExecutiveNarrative.useMutation({
    onSuccess: (data) => {
      setNarrative(data);
      toast.success("Executive narrative generated");
    },
    onError: (error) => {
      toast.error("Failed to generate narrative: " + error.message);
    },
  });

  const promoteMutation = trpc.prism.updateNarrativeTrustState.useMutation({
    onSuccess: () => {
      if (narrative) {
        setNarrative({ ...narrative, trustState: targetTrustState });
      }
      toast.success(`Narrative promoted to ${targetTrustState}`);
      setShowPromoteDialog(false);
      setApprovalNotes("");
    },
    onError: (error) => {
      toast.error("Failed to promote: " + error.message);
    },
  });

  const handleGenerate = () => {
    generateMutation.mutate({
      scope,
      scopeId: scope === "agency" ? selectedAgency : undefined,
    });
  };

  const handlePromote = () => {
    if (narrative) {
      promoteMutation.mutate({
        narrativeId: narrative.id || `NRR-${Date.now()}`,
        newState: targetTrustState,
        approvalNotes,
      });
    }
  };

  const handleCopyNarrative = () => {
    if (narrative) {
      navigator.clipboard.writeText(narrative.narrative);
      toast.success("Copied to clipboard");
    }
  };

  const handleExportPDF = () => {
    if (!narrative) return;

    const agencyName = scope === "agency" && selectedAgency
      ? agencies?.find((a) => a.code === selectedAgency)?.name
      : null;

    const content = `
EXECUTIVE SUMMARY
================================================================================
Generated: ${new Date(narrative.generatedAt).toLocaleString()}
Scope: ${scope}${agencyName ? ` - ${agencyName}` : ""}
Trust State: ${narrative.trustState.toUpperCase()}

--------------------------------------------------------------------------------

${narrative.narrative}

================================================================================
EVIDENCE BUNDLE
================================================================================
${narrative.evidenceBundle.map((e: any) => `• ${e.metric}: ${formatValue(e.value)}\n  Source: ${e.source}`).join("\n\n")}

--------------------------------------------------------------------------------
Generated by PRISM FinOps Intelligence using Snowflake Cortex AI.
    `.trim();

    const blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `executive_report_${scope}_${new Date().toISOString().split("T")[0]}.txt`;
    link.click();

    toast.success("Report exported");
  };

  const currentTrustIndex = narrative
    ? trustStates.findIndex((t) => t.value === narrative.trustState)
    : -1;

  const selectedAgencyName = selectedAgency
    ? agencies?.find((a) => a.code === selectedAgency)?.name
    : undefined;

  const isExecutivePromotion = targetTrustState === "executive";

  if (!isAuthenticated) {
    return (
      <PrismLayout title="Executive Reports">
        <div className="container py-8">
          <Card className="bg-[#161b22] border-[#30363d]">
            <CardContent className="py-12 text-center">
              <Shield className="h-12 w-12 mx-auto mb-4 text-[#8b949e]" />
              <h3 className="text-lg font-semibold text-[#c9d1d9] mb-2">Authentication Required</h3>
              <p className="text-[#8b949e] mb-6">
                Sign in to generate AI-powered executive narratives
              </p>
              <Button asChild className="bg-[#58a6ff] text-[#0d1117] hover:bg-[#388bfd]">
                <a href={getLoginUrl()}>Sign In</a>
              </Button>
            </CardContent>
          </Card>
        </div>
      </PrismLayout>
    );
  }

  return (
    <PrismLayout 
      title="Executive Reports" 
      agencyCode={selectedAgency}
      agencyName={selectedAgencyName}
      trustState={narrative?.trustState || "draft"}
    >
      <div className="container py-6">
        {/* Configuration - Simplified */}
        <Card className="bg-[#161b22] border-[#30363d] mb-6">
          <CardContent className="pt-6">
            <div className="flex flex-wrap items-end gap-4">
              {/* Scope Selection */}
              <div className="space-y-1.5 min-w-[180px]">
                <label className="text-xs text-[#6e7681]">Report Scope</label>
                <Select value={scope} onValueChange={(v: any) => setScope(v)}>
                  <SelectTrigger className="bg-[#0d1117] border-[#30363d] h-9">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-[#161b22] border-[#30363d]">
                    <SelectItem value="government-wide">
                      <div className="flex items-center gap-2">
                        <Globe className="h-4 w-4" />
                        Government-wide
                      </div>
                    </SelectItem>
                    <SelectItem value="portfolio">
                      <div className="flex items-center gap-2">
                        <Briefcase className="h-4 w-4" />
                        Portfolio
                      </div>
                    </SelectItem>
                    <SelectItem value="agency">
                      <div className="flex items-center gap-2">
                        <Building2 className="h-4 w-4" />
                        Single Agency
                      </div>
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Agency Selection */}
              {scope === "agency" && (
                <div className="space-y-1.5 min-w-[240px]">
                  <label className="text-xs text-[#6e7681]">Select Agency</label>
                  <Select value={selectedAgency} onValueChange={setSelectedAgency}>
                    <SelectTrigger className="bg-[#0d1117] border-[#30363d] h-9">
                      <SelectValue placeholder="Choose an agency" />
                    </SelectTrigger>
                    <SelectContent className="bg-[#161b22] border-[#30363d] max-h-[300px]">
                      {agencies?.slice(0, 50).map((agency) => (
                        <SelectItem key={agency.code} value={agency.code}>
                          {agency.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              )}

              {/* Generate Button */}
              <Button
                onClick={handleGenerate}
                disabled={generateMutation.isPending || (scope === "agency" && !selectedAgency)}
                className="bg-[#58a6ff] text-[#0d1117] hover:bg-[#388bfd] h-9"
              >
                {generateMutation.isPending ? (
                  <>
                    <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4 mr-2" />
                    Generate Report
                  </>
                )}
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Generated Narrative */}
        {narrative && (
          <div className="space-y-6">
            {/* Main Narrative Card - Focus on "What" */}
            <Card className="bg-[#161b22] border-[#30363d]">
              <CardHeader className="pb-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <TrustStateBadge state={narrative.trustState} />
                    <span className="text-xs text-[#6e7681]">
                      Generated {new Date(narrative.generatedAt).toLocaleString()}
                    </span>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleCopyNarrative}
                      className="text-[#8b949e] hover:text-[#c9d1d9] h-8"
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleExportPDF}
                      className="text-[#8b949e] hover:text-[#c9d1d9] h-8"
                    >
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="prose prose-invert max-w-none">
                  <div className="text-[#c9d1d9] leading-relaxed">
                    <Streamdown>{narrative.narrative}</Streamdown>
                  </div>
                </div>

                {/* Key Metrics - Inline summary */}
                <div className="mt-6 pt-6 border-t border-[#30363d]">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    {narrative.evidenceBundle.slice(0, 4).map((evidence: any, index: number) => (
                      <div key={index} className="text-center">
                        <div className="text-lg font-semibold text-[#c9d1d9]">
                          {formatValue(evidence.value)}
                        </div>
                        <div className="text-xs text-[#6e7681]">{evidence.metric}</div>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Trust State Actions - Only show when narrative exists */}
            <Card className="bg-[#161b22] border-[#30363d]">
              <CardContent className="py-4">
                <div className="flex items-center justify-between">
                  {/* Compact Trust State Progress */}
                  <div className="flex items-center gap-2">
                    {trustStates.map((state, index) => {
                      const isActive = state.value === narrative.trustState;
                      const isPast = index < currentTrustIndex;
                      const Icon = state.icon;

                      return (
                        <div key={state.value} className="flex items-center">
                          <div
                            className={`w-8 h-8 rounded-full flex items-center justify-center ${
                              isActive
                                ? "ring-2 ring-offset-2 ring-offset-[#161b22]"
                                : ""
                            } ${
                              isPast
                                ? "bg-[#3fb950]/20"
                                : isActive
                                ? "bg-current/20"
                                : "bg-[#21262d]"
                            }`}
                            style={{ 
                              borderColor: isActive ? state.color : undefined,
                            }}
                          >
                            {isPast ? (
                              <Check className="h-4 w-4 text-[#3fb950]" />
                            ) : (
                              <Icon
                                className="h-4 w-4"
                                style={{ color: isActive ? state.color : "#6e7681" }}
                              />
                            )}
                          </div>
                          {index < trustStates.length - 1 && (
                            <div
                              className={`w-8 h-0.5 ${
                                index < currentTrustIndex ? "bg-[#3fb950]" : "bg-[#30363d]"
                              }`}
                            />
                          )}
                        </div>
                      );
                    })}
                    <span className="ml-3 text-sm text-[#8b949e]">
                      {trustStates[currentTrustIndex]?.description}
                    </span>
                  </div>

                  {/* Promote Button */}
                  {currentTrustIndex < trustStates.length - 1 && (
                    <Button
                      size="sm"
                      onClick={() => {
                        setTargetTrustState(trustStates[currentTrustIndex + 1].value);
                        setShowPromoteDialog(true);
                      }}
                      className="bg-[#238636] text-white hover:bg-[#2ea043]"
                    >
                      <ChevronRight className="h-4 w-4 mr-1" />
                      Promote to {trustStates[currentTrustIndex + 1]?.label}
                    </Button>
                  )}
                  {currentTrustIndex === trustStates.length - 1 && (
                    <Badge className="bg-[#3fb950]/20 text-[#3fb950] border-[#3fb950]">
                      <Check className="h-3 w-3 mr-1" />
                      Executive Approved
                    </Badge>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Evidence Details - Collapsible (hidden by default) */}
            <Collapsible open={showEvidenceDetails} onOpenChange={setShowEvidenceDetails}>
              <Card className="bg-[#161b22] border-[#30363d]">
                <CollapsibleTrigger asChild>
                  <CardHeader className="cursor-pointer hover:bg-[#21262d]/50 transition-colors">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <Database className="h-4 w-4 text-[#58a6ff]" />
                        <CardTitle className="text-sm text-[#c9d1d9]">Evidence & Sources</CardTitle>
                      </div>
                      <ChevronDown className={`h-4 w-4 text-[#8b949e] transition-transform ${showEvidenceDetails ? "rotate-180" : ""}`} />
                    </div>
                  </CardHeader>
                </CollapsibleTrigger>
                <CollapsibleContent>
                  <CardContent className="pt-0">
                    <div className="grid md:grid-cols-2 gap-4">
                      {/* Evidence Bundle */}
                      <div className="space-y-3">
                        <h4 className="text-xs text-[#6e7681] uppercase tracking-wide">Data Points</h4>
                        {narrative.evidenceBundle.map((evidence: any, index: number) => (
                          <div
                            key={index}
                            className="p-3 rounded-lg bg-[#0d1117] border border-[#30363d]"
                          >
                            <div className="flex items-center justify-between">
                              <span className="text-sm text-[#8b949e]">{evidence.metric}</span>
                              <span className="text-sm font-medium text-[#c9d1d9]">
                                {formatValue(evidence.value)}
                              </span>
                            </div>
                            <div className="text-xs text-[#6e7681] mt-1 flex items-center gap-1">
                              <Database className="h-3 w-3" />
                              {evidence.source}
                            </div>
                          </div>
                        ))}
                      </div>

                      {/* Citations */}
                      {narrative.citations && narrative.citations.length > 0 && (
                        <div className="space-y-3">
                          <h4 className="text-xs text-[#6e7681] uppercase tracking-wide">Citations</h4>
                          <div className="space-y-2">
                            {narrative.citations.map((citation: string, index: number) => (
                              <div
                                key={index}
                                className="text-sm text-[#8b949e] flex items-start gap-2 p-2 rounded bg-[#0d1117]"
                              >
                                <span className="text-[#58a6ff] font-mono text-xs">[{index + 1}]</span>
                                <span className="text-xs">{citation}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  </CardContent>
                </CollapsibleContent>
              </Card>
            </Collapsible>
          </div>
        )}

        {/* Empty State - Simplified */}
        {!narrative && !generateMutation.isPending && (
          <Card className="bg-[#161b22] border-[#30363d]">
            <CardContent className="py-12 text-center">
              <FileText className="h-10 w-10 mx-auto mb-4 text-[#6e7681]" />
              <h3 className="text-base font-medium text-[#c9d1d9] mb-2">Generate an Executive Report</h3>
              <p className="text-sm text-[#8b949e] max-w-md mx-auto">
                Select a scope above and click "Generate Report" to create an AI-powered executive summary
              </p>
            </CardContent>
          </Card>
        )}

        {/* Promote Dialog - Enhanced for Executive approval */}
        <Dialog open={showPromoteDialog} onOpenChange={setShowPromoteDialog}>
          <DialogContent className="bg-[#161b22] border-[#30363d] max-w-lg">
            <DialogHeader>
              <DialogTitle className="text-[#c9d1d9] flex items-center gap-2">
                {isExecutivePromotion && <Lock className="h-5 w-5 text-[#d29922]" />}
                Promote to {targetTrustState}
              </DialogTitle>
              <DialogDescription className="text-[#8b949e]">
                {isExecutivePromotion
                  ? "Executive promotion requires human approval. This action will be logged for audit and compliance."
                  : "This action will be logged for audit purposes."}
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-4">
              {/* Executive Warning */}
              {isExecutivePromotion && (
                <div className="p-4 rounded-lg bg-[#d29922]/10 border border-[#d29922]/30">
                  <div className="flex items-start gap-3">
                    <AlertTriangle className="h-5 w-5 text-[#d29922] flex-shrink-0 mt-0.5" />
                    <div>
                      <p className="text-sm font-medium text-[#d29922]">Human Approval Required</p>
                      <p className="text-xs text-[#8b949e] mt-1">
                        Promoting to Executive status makes this narrative visible to C-suite leadership. 
                        Please verify the content is accurate and appropriate.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* Evidence Preview */}
              <div className="p-4 rounded-lg bg-[#0d1117] border border-[#30363d]">
                <h4 className="text-xs text-[#6e7681] uppercase tracking-wide mb-3">Evidence Preview</h4>
                <div className="space-y-2">
                  {narrative?.evidenceBundle.slice(0, 3).map((evidence: any, index: number) => (
                    <div key={index} className="flex items-center justify-between text-sm">
                      <span className="text-[#8b949e]">{evidence.metric}</span>
                      <span className="text-[#c9d1d9] font-medium">{formatValue(evidence.value)}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Agreement Reference */}
              <div className="p-3 rounded-lg bg-[#0d1117] border border-[#30363d] flex items-center gap-3">
                <Shield className="h-4 w-4 text-[#58a6ff]" />
                <div className="text-xs">
                  <span className="text-[#8b949e]">Governed by: </span>
                  <span className="text-[#c9d1d9]">Federal Data Use Agreement (DULA)</span>
                </div>
              </div>

              {/* Approval Notes */}
              <div className="space-y-2">
                <label className="text-sm text-[#8b949e]">
                  {isExecutivePromotion ? "Approval Reason (Required)" : "Notes (Optional)"}
                </label>
                <Textarea
                  value={approvalNotes}
                  onChange={(e) => setApprovalNotes(e.target.value)}
                  placeholder={isExecutivePromotion 
                    ? "Describe why this narrative is ready for executive distribution..."
                    : "Add any notes about this promotion..."
                  }
                  className="bg-[#0d1117] border-[#30363d] text-[#c9d1d9] placeholder:text-[#6e7681]"
                  rows={3}
                />
              </div>
            </div>

            <DialogFooter>
              <Button
                variant="outline"
                onClick={() => setShowPromoteDialog(false)}
                className="border-[#30363d] text-[#c9d1d9] hover:bg-[#21262d]"
              >
                Cancel
              </Button>
              <Button
                onClick={handlePromote}
                disabled={promoteMutation.isPending || (isExecutivePromotion && !approvalNotes.trim())}
                className={isExecutivePromotion 
                  ? "bg-[#d29922] text-[#0d1117] hover:bg-[#d29922]/80"
                  : "bg-[#238636] text-white hover:bg-[#2ea043]"
                }
              >
                {promoteMutation.isPending ? (
                  <>
                    <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                    Promoting...
                  </>
                ) : (
                  <>
                    <Check className="h-4 w-4 mr-2" />
                    {isExecutivePromotion ? "Approve & Promote" : "Confirm Promotion"}
                  </>
                )}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </PrismLayout>
  );
}

function TrustStateBadge({ state }: { state: TrustState }) {
  const trustState = trustStates.find((t) => t.value === state);
  if (!trustState) return null;

  const Icon = trustState.icon;

  return (
    <Badge
      variant="outline"
      className="border-current"
      style={{ borderColor: trustState.color, color: trustState.color }}
    >
      <Icon className="h-3 w-3 mr-1" />
      {trustState.label}
    </Badge>
  );
}

function formatValue(value: number): string {
  if (value >= 1e12) return `$${(value / 1e12).toFixed(2)}T`;
  if (value >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
  if (value >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
  if (value >= 1000) return value.toLocaleString();
  return value.toString();
}
