-- Staging view for CIW spending data
-- Replaces EOTSS_STAGING.V_CIW_SPENDING
-- Adds computed columns: UNLIQUIDATED_OBLIGATIONS, BURN_RATE_PCT
SELECT
    RECORD_ID,
    AGENCY_CODE,
    AGENCY_NAME,
    SECRETARIAT_ID,
    FUND_CODE,
    FUND_NAME,
    FISCAL_PERIOD_DATE,
    FISCAL_YEAR_LABEL,
    TOTAL_OBLIGATIONS,
    TOTAL_EXPENDITURES,
    BUDGET_AUTHORITY,
    ROUND(TOTAL_OBLIGATIONS - TOTAL_EXPENDITURES, 2) AS UNLIQUIDATED_OBLIGATIONS,
    CASE
        WHEN BUDGET_AUTHORITY > 0
        THEN ROUND(LEAST(TOTAL_EXPENDITURES / BUDGET_AUTHORITY * 100, 999.99), 2)
        ELSE 0
    END AS BURN_RATE_PCT
FROM {{ source('eotss_poc', 'CIW_SPENDING') }}
