-- Staging view for CTHR workforce data
-- Replaces EOTSS_STAGING.V_CTHR_WORKFORCE
SELECT
    RECORD_ID,
    AGENCY_CODE,
    AGENCY_NAME,
    SECRETARIAT_ID,
    JOB_CLASSIFICATION,
    REPORTING_PERIOD_DATE,
    POSITION_COUNT,
    FILLED_POSITIONS,
    SALARY_OBLIGATIONS,
    VACANCY_RATE
FROM {{ source('eotss_poc', 'CTHR_WORKFORCE') }}
