-- Staging view for CIP investment data
-- Replaces EOTSS_STAGING.V_CIP_INVESTMENTS
-- Adds computed columns: VARIANCE_AMOUNT, VARIANCE_PCT
SELECT
    PROJECT_ID,
    PROJECT_NAME,
    AGENCY_CODE,
    AGENCY_NAME,
    SECRETARIAT,
    POLICY_AREA,
    PROJECT_STATUS,
    FISCAL_YEAR_START,
    FISCAL_YEAR_START_DATE,
    FISCAL_YEAR_END,
    PLANNED_BUDGET,
    ACTUAL_SPEND,
    PERCENT_COMPLETE,
    PROJECT_MANAGER,
    ROUND(ACTUAL_SPEND - PLANNED_BUDGET, 2) AS VARIANCE_AMOUNT,
    CASE
        WHEN PLANNED_BUDGET > 0
        THEN ROUND((ACTUAL_SPEND - PLANNED_BUDGET) / PLANNED_BUDGET * 100, 2)
        ELSE 0
    END AS VARIANCE_PCT
FROM {{ source('eotss_poc', 'CIP_INVESTMENTS') }}
