-- ============================================================================
-- PRISM FinOps - Multi-Tenant Configuration
-- Schema-per-tenant isolation with per-tenant Snowflake roles
-- ============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE FEDERAL_FINANCIAL_DATA;

-- ============================================================================
-- 1. TENANT REGISTRY TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS GOVERNANCE.TENANTS (
    TENANT_ID       VARCHAR(64)   NOT NULL PRIMARY KEY,
    DISPLAY_NAME    VARCHAR(256)  NOT NULL,
    DATA_SCHEMA     VARCHAR(128)  NOT NULL,
    GOV_SCHEMA      VARCHAR(128)  NOT NULL DEFAULT 'GOVERNANCE',
    SEM_SCHEMA      VARCHAR(128)  NOT NULL DEFAULT 'SEMANTIC',
    SNOWFLAKE_ROLE  VARCHAR(128)  NOT NULL,
    IS_ACTIVE       BOOLEAN       NOT NULL DEFAULT TRUE,
    CREATED_AT      TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================================
-- 2. USER-TO-TENANT MAPPING TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS GOVERNANCE.TENANT_USERS (
    USER_ID         VARCHAR(256)  NOT NULL,
    TENANT_ID       VARCHAR(64)   NOT NULL,
    ASSIGNED_AT     TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ASSIGNED_BY     VARCHAR(256),
    PRIMARY KEY (USER_ID, TENANT_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES GOVERNANCE.TENANTS(TENANT_ID)
);

-- ============================================================================
-- 3. SEED EOTSS TENANT (lowercase tenant ID)
-- ============================================================================

INSERT INTO GOVERNANCE.TENANTS (TENANT_ID, DISPLAY_NAME, DATA_SCHEMA, GOV_SCHEMA, SEM_SCHEMA, SNOWFLAKE_ROLE)
    SELECT 'eotss', 'Executive Office of Technology Services and Security', 'EOTSS_STAGING', 'GOVERNANCE', 'SEMANTIC', 'PRISM_TENANT_EOTSS_ROLE'
    WHERE NOT EXISTS (SELECT 1 FROM GOVERNANCE.TENANTS WHERE TENANT_ID = 'eotss');

-- Seed dev user mapping (matches DEV_USER openId in sdk.ts)
INSERT INTO GOVERNANCE.TENANT_USERS (USER_ID, TENANT_ID, ASSIGNED_BY)
    SELECT 'dev-user-001', 'eotss', 'system'
    WHERE NOT EXISTS (SELECT 1 FROM GOVERNANCE.TENANT_USERS WHERE USER_ID = 'dev-user-001');

-- Seed SPCS user mapping
INSERT INTO GOVERNANCE.TENANT_USERS (USER_ID, TENANT_ID, ASSIGNED_BY)
    SELECT 'spcs-authenticated-user', 'eotss', 'system'
    WHERE NOT EXISTS (SELECT 1 FROM GOVERNANCE.TENANT_USERS WHERE USER_ID = 'spcs-authenticated-user');

-- ============================================================================
-- 4. PER-TENANT ROLE: PRISM_TENANT_EOTSS_ROLE
-- ============================================================================

CREATE ROLE IF NOT EXISTS PRISM_TENANT_EOTSS_ROLE
    COMMENT = 'Tenant role for EOTSS - scoped to EOTSS_STAGING, GOVERNANCE, SEMANTIC schemas';

-- Grant warehouse usage (same warehouse, role-scoped access)
GRANT USAGE ON WAREHOUSE PRISM_APP_WH TO ROLE PRISM_TENANT_EOTSS_ROLE;

-- Grant database-level USAGE (required to access any schema)
GRANT USAGE ON DATABASE FEDERAL_FINANCIAL_DATA TO ROLE PRISM_TENANT_EOTSS_ROLE;

-- Scoped schema grants: EOTSS_STAGING (data)
GRANT USAGE ON SCHEMA FEDERAL_FINANCIAL_DATA.EOTSS_STAGING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.EOTSS_STAGING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.EOTSS_STAGING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.EOTSS_STAGING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.EOTSS_STAGING TO ROLE PRISM_TENANT_EOTSS_ROLE;

-- Scoped schema grants: GOVERNANCE
GRANT USAGE ON SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_TENANT_EOTSS_ROLE;
-- Allow INSERT for audit tables within GOVERNANCE
GRANT INSERT ON ALL TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_TENANT_EOTSS_ROLE;

-- Scoped schema grants: SEMANTIC
GRANT USAGE ON SCHEMA FEDERAL_FINANCIAL_DATA.SEMANTIC TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.SEMANTIC TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.SEMANTIC TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.SEMANTIC TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.SEMANTIC TO ROLE PRISM_TENANT_EOTSS_ROLE;

-- Scoped schema grants: USASPENDING (read-only data access)
GRANT USAGE ON SCHEMA FEDERAL_FINANCIAL_DATA.USASPENDING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.USASPENDING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.USASPENDING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.USASPENDING TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.USASPENDING TO ROLE PRISM_TENANT_EOTSS_ROLE;

-- Scoped schema grants: ANALYTICS (read-only for anomaly/forecast results)
GRANT USAGE ON SCHEMA FEDERAL_FINANCIAL_DATA.ANALYTICS TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.ANALYTICS TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.ANALYTICS TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.ANALYTICS TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA FEDERAL_FINANCIAL_DATA.ANALYTICS TO ROLE PRISM_TENANT_EOTSS_ROLE;
-- Allow UPDATE for anomaly acknowledgments
GRANT UPDATE ON ALL TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.ANALYTICS TO ROLE PRISM_TENANT_EOTSS_ROLE;
GRANT UPDATE ON FUTURE TABLES IN SCHEMA FEDERAL_FINANCIAL_DATA.ANALYTICS TO ROLE PRISM_TENANT_EOTSS_ROLE;

-- Grant the tenant role to the app role (role hierarchy)
GRANT ROLE PRISM_TENANT_EOTSS_ROLE TO ROLE PRISM_APP_ROLE;

-- ============================================================================
-- 5. PRISM_APP_ROLE retains GOVERNANCE.TENANTS/TENANT_USERS read access
--    (needed for tenant resolution at connection time)
-- ============================================================================

GRANT USAGE ON SCHEMA FEDERAL_FINANCIAL_DATA.GOVERNANCE TO ROLE PRISM_APP_ROLE;
GRANT SELECT ON TABLE FEDERAL_FINANCIAL_DATA.GOVERNANCE.TENANTS TO ROLE PRISM_APP_ROLE;
GRANT SELECT ON TABLE FEDERAL_FINANCIAL_DATA.GOVERNANCE.TENANT_USERS TO ROLE PRISM_APP_ROLE;
